application: gotfmt
version: 2
runtime: go
api_version: go1

handlers:
- url: /process
  script: _go_app

- url: /
  static_files: static/index.html
  upload: static

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
- url: /(.*\.map)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.map)
